//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartMentStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_id { get; set; }
        public Nullable<int> ProId { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<int> NId { get; set; }
        public Nullable<decimal> Point { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
